# Generated by Django 2.2.19 on 2021-09-17 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='files/<django.db.models.fields.CharField>')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date uploaded')),
                ('tokens_counter', models.IntegerField(verbose_name='count of tokens in file')),
                ('ownen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=200)),
                ('tf_idf', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FileToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf', models.FloatField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.File')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.Token')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='token',
            field=models.ManyToManyField(through='file.FileToken', to='file.Token'),
        ),
    ]
