# Generated by Django 2.2.19 on 2021-09-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='tf_idf',
        ),
        migrations.AddField(
            model_name='token',
            name='idf',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files/', verbose_name='Текстовый файл'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='file',
            name='token',
            field=models.ManyToManyField(default=None, through='file.FileToken', to='file.Token'),
        ),
        migrations.AlterField(
            model_name='file',
            name='tokens_counter',
            field=models.IntegerField(default=0, verbose_name='count of tokens in file'),
        ),
        migrations.AlterField(
            model_name='filetoken',
            name='tf',
            field=models.FloatField(default=None),
        ),
    ]
