# Generated by Django 2.2.19 on 2021-09-18 15:51

from django.db import migrations, models
import django.db.models.deletion
import file.models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20210918_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='ownen',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=file.models.user_directory_path, verbose_name='Текстовый файл'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='filetoken',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_token', to='file.File'),
        ),
        migrations.AlterField(
            model_name='token',
            name='idf',
            field=models.FloatField(default=0),
        ),
    ]
