# Generated by Django 2.2.19 on 2021-09-18 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_auto_20210918_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filetoken',
            options={'ordering': ['-token__idf']},
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['-idf']},
        ),
        migrations.AlterField(
            model_name='filetoken',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='file.Token'),
        ),
    ]
